Repository keboola/keboola-as-code, pull requests merged in 2024-05, with the labels that each got.

#1765 feat: Add a new field `appSlug`
  internal/pkg/service/appsproxy/dataapps/api/config.go
  internal/pkg/service/appsproxy/proxy/proxy_test.go
  internal/pkg/service/appsproxy/proxy/server_test.go
Labels: apps-proxy

#1771 fix: Order of callbacks invocations, if TxnOp.Merge is used
  internal/pkg/service/common/etcdop/key.go
  internal/pkg/service/common/etcdop/op/txn.go
  internal/pkg/service/common/etcdop/op/txn_error.go
  internal/pkg/service/common/etcdop/op/txn_error_test.go
  internal/pkg/service/common/etcdop/op/txn_test.go
Labels: streams-R1

#1773 feat: Improve etcd helpers
  .gitignore
  build/ci/golangci.yml
  internal/pkg/service/common/utctime/utctime.go
  internal/pkg/utils/etcdhelper/assert.go
  internal/pkg/utils/etcdhelper/assert_test.go
  internal/pkg/utils/etcdhelper/dump.go
  internal/pkg/utils/etcdhelper/fixtures/expected-001.txt
  internal/pkg/utils/etcdlogger/assert.go
  scripts/tools.sh
Labels: streams-R1

#1774 feat: Improve definition entities
  internal/pkg/service/stream/definition/branch.go
  internal/pkg/service/stream/definition/by.go
  internal/pkg/service/stream/definition/sink_base.go
  internal/pkg/service/stream/definition/sink_table.go
  internal/pkg/service/stream/definition/sink_table_test.go
  internal/pkg/service/stream/definition/softdeletable.go
  internal/pkg/service/stream/definition/softdeletable_test.go
  internal/pkg/service/stream/definition/source_base.go
  internal/pkg/service/stream/definition/source_http_test.go
  internal/pkg/service/stream/definition/switchable.go
  internal/pkg/service/stream/definition/switchable_test.go
  internal/pkg/service/stream/definition/versioned.go
  internal/pkg/service/stream/definition/versioned_test.go
  internal/pkg/service/stream/mapping/table/column/body.go
  internal/pkg/service/stream/mapping/table/column/column.go
  internal/pkg/service/stream/mapping/table/column/column_test.go
  internal/pkg/service/stream/mapping/table/column/datetime.go
  internal/pkg/service/stream/mapping/table/column/headers.go
  internal/pkg/service/stream/mapping/table/column/ip.go
  internal/pkg/service/stream/mapping/table/column/renderer.go
  internal/pkg/service/stream/mapping/table/column/renderer_benchmark_test.go
  internal/pkg/service/stream/mapping/table/column/renderer_test.go
  internal/pkg/service/stream/mapping/table/column/template.go
  internal/pkg/service/stream/mapping/table/column/uuid.go
  internal/pkg/service/stream/mapping/table/mapping_test.go
Labels: streams-R1

#1776 CLI: Ignoring branch name for push command by manifest field `allowTargetEnv`
  internal/pkg/plan/push/push.go
  pkg/lib/operation/project/sync/push/operation.go
  test/cli/push/ok-ignoring-branch-name/args
  test/cli/push/ok-ignoring-branch-name/env
  test/cli/push/ok-ignoring-branch-name/expected-code
  test/cli/push/ok-ignoring-branch-name/expected-state.json
  test/cli/push/ok-ignoring-branch-name/expected-stderr
  test/cli/push/ok-ignoring-branch-name/expected-stdout
  test/cli/push/ok-ignoring-branch-name/in/.keboola/manifest.json
  test/cli/push/ok-ignoring-branch-name/in/foo/description.md
  test/cli/push/ok-ignoring-branch-name/in/foo/meta.json
  test/cli/push/ok-ignoring-branch-name/initial-state.json
  test/cli/push/ok-ignoring-branch-name/out/.gitkeep
  test/cli/push/ok-ignoring-branch-name/out/.keboola/manifest.json
  test/cli/push/ok-ignoring-branch-name/out/foo/description.md
  test/cli/push/ok-ignoring-branch-name/out/foo/meta.json
Labels: CLI
